name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - test  # or whichever branch should trigger the deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Re-Deploy Pythonanywhere Django API
        uses: umuttopalak/pythonanywhere-deploy-action@v1.1.2
        with:
          host: www.pythonanywhere.com
          username: cqyao
          api_token: ${{ secrets.PYTHONANYWHERE_API_TOKEN }}
